export const en = {
  locale: 'en',
  title: 'Personal AI Agent | lninl',
  hero: 'An AI agent built around you.',
  intro: 'Give your agent the context that matters: your goals, preferences, and the things you want to remember. Think together, then approve every action.',
  eyebrow: 'PERSONAL AI, ON YOUR TERMS',
  cta: 'Create your agent',
  learn: 'How it works',
  navHow: 'The idea',
  navPrivacy: 'Your control',
  navGuide: 'Guide',
  switchLanguage: '中文',
  personal: 'Personal by design',
  personalText: 'A generic chatbot starts from a blank page. Your personal AI agent starts with the context you choose to share.',
  memory: 'A memory you can edit',
  memoryText: 'Add what matters, change what no longer fits, and delete anything at any time.',
  action: 'Actions need your approval',
  actionText: 'The agent can suggest task changes. Nothing is applied until you confirm the exact change.',
  privacy: 'Your context stays yours.',
  privacyText: 'Your profile, memories, tasks, and conversations live in this browser. Your API key is used only during the current page session. Model requests send selected context to OpenAI through our Rust gateway; the gateway does not store your data or key.',
  useCasesTitle: 'A useful place to begin',
  useCases: [
    ['Plan with context', 'Turn a long-term goal into a manageable next step, without explaining yourself from scratch each time.'],
    ['Keep track of what matters', 'Maintain explicit memories and tasks that you can always inspect and change.'],
    ['Stay in control', 'Review proposed actions before they touch your task list.'],
  ],
  faqTitle: 'Questions, answered',
  faqs: [
    ['What is a Personal AI Agent?', 'An AI assistant configured around one person: their context, goals, preferences, and approved actions.'],
    ['Is this just another chatbot?', 'Conversation is one part. Your editable memory and approval-based task actions give it continuity and a bounded way to help.'],
    ['Do I need an account?', 'No. First-release data stays in this browser. Export it before changing devices or clearing browser storage.'],
    ['Which model does it use?', 'Bring your own OpenAI API key. The key is not stored, so you will enter it again after a refresh.'],
  ],
  guideTitle: 'What is a Personal AI Agent?',
  guideLead: 'A personal AI agent is software that uses the context you choose to provide to help with your goals and, within clear boundaries, propose useful actions.',
  guideSections: [
    ['Beyond one-off answers', 'A conventional chatbot responds to the current prompt. A personal agent can also use your saved preferences, goals, and explicit memories to keep advice relevant over time.'],
    ['Memory should be legible', 'Useful personalization requires control. In lninl, you can see and edit every saved memory; the agent does not silently write new memories from your conversations.'],
    ['Action without surprise', 'In this first release the agent can propose changes to your task list. You see the proposed change before approving it. It cannot send email, operate your accounts, or execute arbitrary commands.'],
    ['Local-first, not magic sync', 'Your personal data is stored in your current browser, not in an lninl account. You can export or import it. There is no cross-device sync yet.'],
  ],
  footer: 'Built for one person at a time.',
} as const;
