export const en = {
  locale: 'en',
  title: 'Personal AI Agent | lninl',
  hero: 'An AI agent that moves with you.',
  intro: 'Give your agent the context that matters, track a goal, and check in on what changed. Use each outcome to choose a better next step, with every task change under your control.',
  loopLabel: 'Goal → action → check-in → next step',
  eyebrow: 'PERSONAL AI, ON YOUR TERMS',
  cta: 'Create your agent',
  learn: 'How it works',
  navHow: 'The idea',
  navPrivacy: 'Your control',
  navGuide: 'Guide',
  switchLanguage: '中文',
  personal: 'Personal by design',
  personalText: 'A generic chatbot answers one prompt. Your personal AI agent can use the goals, actions, and check-ins you choose to save across conversations.',
  memory: 'A memory you can edit',
  memoryText: 'Add what matters, change what no longer fits, and delete anything at any time.',
  action: 'Actions need your approval',
  actionText: 'The agent can suggest task changes. Nothing is applied until you confirm the exact change.',
  privacy: 'Your context stays yours.',
  privacyText: 'Your profile, goals, check-ins, memories, tasks, and conversations live in this browser. Your API key is used only during the current page session. Model requests send selected context to your chosen API endpoint through our Rust gateway; the gateway does not store your data or key. Check your provider’s data policy separately.',
  useCasesTitle: 'A useful place to begin',
  useCases: [
    ['Keep a goal moving', 'Record its stage, next action, and a date to check in. A due review is shown when you open the workspace.'],
    ['Learn from what happened', 'Save check-ins and use their outcomes to inform later conversations. You decide what becomes a memory or task.'],
    ['Stay in control', 'Review proposed actions before they touch your task list.'],
  ],
  faqTitle: 'Questions, answered',
  faqs: [
    ['What is a Personal AI Agent?', 'An AI assistant organized around one person: their context, evolving goals, recorded outcomes, and approved actions.'],
    ['Is this just another chatbot?', 'No. A goal, action, and check-in loop gives later conversations a record of what happened, not only what you asked.'],
    ['Do I need an account?', 'No. Your data stays in this browser. Export it before changing devices or clearing browser storage. There is no automatic sync.'],
    ['Which model does it use?', 'Choose an OpenAI-compatible Responses or Chat Completions endpoint (including DeepSeek), or Anthropic Messages. Enter its full API URL, model ID, and your own API key. These settings are not stored.'],
  ],
  guideTitle: 'What is a Personal AI Agent?',
  guideLead: 'A personal AI agent uses the context and outcomes you choose to record to help you keep moving toward a goal, within clear boundaries.',
  guideSections: [
    ['From goal to next step', 'Set a goal and its current stage, take an action, then record what happened. Later conversations can use recent check-ins to help reassess the next step rather than restart from a blank prompt.'],
    ['Across your contexts', 'Label goals and memories as work, learning, life, or other. The agent may draw on selected context across domains, but it does not autonomously collect activity from other apps.'],
    ['Memory should be legible', 'Useful personalization requires control. In lninl, you can see and edit every saved memory; the agent does not silently write new memories from your conversations.'],
    ['Action without surprise', 'The agent can propose changes to your task list. You see the proposed change before approving it. It cannot send email, operate your accounts, or execute arbitrary commands.'],
    ['Local-first, not magic sync', 'Your personal data is stored in your current browser, not in an lninl account. You can export or import it. There are no background reminders or cross-device sync yet.'],
  ],
  footer: 'Built for one person at a time.',
} as const;
